// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLq4Bysm0WINGIczkKtFIKgwJ9hlgOH1A',
    appId: '1:1090224728067:web:77e4644100b5119f2c8636',
    messagingSenderId: '1090224728067',
    projectId: 'tarea01-c5ac4',
    authDomain: 'tarea01-c5ac4.firebaseapp.com',
    storageBucket: 'tarea01-c5ac4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFbVAbGmSgkDfc7rsmI2VD44h0D6yALZ4',
    appId: '1:1090224728067:android:23aaf812d4771e432c8636',
    messagingSenderId: '1090224728067',
    projectId: 'tarea01-c5ac4',
    storageBucket: 'tarea01-c5ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH76uSgK4CWJSA2H6vAt3BtKNmzZApIR0',
    appId: '1:1090224728067:ios:5c1de8854b6a83252c8636',
    messagingSenderId: '1090224728067',
    projectId: 'tarea01-c5ac4',
    storageBucket: 'tarea01-c5ac4.appspot.com',
    iosBundleId: 'com.example.tarea01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH76uSgK4CWJSA2H6vAt3BtKNmzZApIR0',
    appId: '1:1090224728067:ios:5c1de8854b6a83252c8636',
    messagingSenderId: '1090224728067',
    projectId: 'tarea01-c5ac4',
    storageBucket: 'tarea01-c5ac4.appspot.com',
    iosBundleId: 'com.example.tarea01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLq4Bysm0WINGIczkKtFIKgwJ9hlgOH1A',
    appId: '1:1090224728067:web:59a410baef3a77d02c8636',
    messagingSenderId: '1090224728067',
    projectId: 'tarea01-c5ac4',
    authDomain: 'tarea01-c5ac4.firebaseapp.com',
    storageBucket: 'tarea01-c5ac4.appspot.com',
  );
}
